version: '3.8'

services:
  spirit-go:
    build: .
    image: spirit-go:1.0.0
    container_name: spirit-go
    restart: always
    ports:
      - "8899:8899"
    volumes:
      - ./config.json:/app/config.json
      - ./static:/app/static
      - ./logs:/app/logs